apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.jobLoaddata.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  template:
    spec:
      containers:
        - name: {{ .Values.backend.name }}
          image: {{ .Values.global.images.api.name }}
          imagePullPolicy: {{ .Values.global.images.api.pullPolicy }}
          command: {{ toJson .Values.jobLoaddata.command }}
          env:
            {{- $global := .Values.global }}
            {{- range $alias, $mapping := .Values.backend.env.secret }}
              {{- range $key, $val := $mapping }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ index $global.secret $alias }}
                  key: {{ $val }}
              {{- end }}
            {{- end }}
            {{- range $alias, $mapping := .Values.backend.env.config }}
              {{- range $key, $val := $mapping }}
            - name: {{ $key }}
              valueFrom:
                configMapKeyRef:
                  name: {{ index $global.config $alias }}
                  key: {{ $val }}
              {{- end }}
            {{- end }}
      restartPolicy: {{ .Values.jobLoaddata.restartPolicy }}
