# Generated by Django 5.2.1 on 2025-06-28 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_ingredient_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='text',
        ),
    ]
